### ISSUE TITLE
make fail

### ISSUE THREAD

**Issue by Intrainos** [BtbN/ZncTwitchTMI#3]
intrainos@irc ~
16:48:31 > $ cd ZncTwitchTMI
intrainos@irc ~/ZncTwitchTMI [±master×] ?  [6897cab]                                              16:48:32 > $ make
[ 16%] Building CXX object CMakeFiles/twitch.dir/twitchtmi.cpp.o
In file included from /usr/include/c++/4.8/bits/hashtable.h:35:0,
                 from /usr/include/c++/4.8/unordered_set:47,
                 from /home/intrainos/ZncTwitchTMI/twitchtmi.h:6,
                 from /home/intrainos/ZncTwitchTMI/twitchtmi.cpp:12:
/usr/include/c++/4.8/bits/hashtable_policy.h: In instantiation of ‘struct std::__detail::_Hash_code_base<CString, CString, std::__detail::_Identity, std::hash<CString>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, true>’:
/usr/include/c++/4.8/bits/hashtable_policy.h:1402:10:   required from ‘struct std::__detail::_Hashtable_base<CString, CString, std::__detail::_Identity, std::equal_to<CString>, std::hash<CString>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Hashtable_traits<true, true, true> >’
/usr/include/c++/4.8/bits/hashtable.h:174:11:   required from ‘class std::_Hashtable<CString, CString, std::allocator<CString>, std::__detail::_Identity, std::equal_to<CString>, std::hash<CString>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, true, true> >’
/usr/include/c++/4.8/bits/unordered_set.h:96:18:   required from ‘class std::unordered_set<CString>’
/home/intrainos/ZncTwitchTMI/twitchtmi.h:41:30:   required from here
/usr/include/c++/4.8/bits/hashtable_policy.h:1070:12: error: invalid use of incomplete type ‘struct std::hash<CString>’
     struct _Hash_code_base<_Key, _Value, _ExtractKey, _H1, _H2,
            ^
In file included from /usr/include/c++/4.8/bits/basic_string.h:3033:0,
                 from /usr/include/c++/4.8/string:52,
                 from /usr/include/c++/4.8/stdexcept:39,
                 from /usr/include/c++/4.8/array:38,
                 from /usr/include/c++/4.8/tuple:39,
                 from /usr/include/c++/4.8/bits/stl_map.h:63,
                 from /usr/include/c++/4.8/map:61,
                 from /usr/local/include/znc/ZNCString.h:21,
                 from /usr/local/include/znc/Utils.h:21,
                 from /usr/local/include/znc/User.h:21,
                 from /home/intrainos/ZncTwitchTMI/twitchtmi.cpp:2:
/usr/include/c++/4.8/bits/functional_hash.h:58:12: error: declaration of ‘struct std::hash<CString>’
     struct hash;
            ^
In file included from /usr/include/c++/4.8/bits/hashtable.h:35:0,
                 from /usr/include/c++/4.8/unordered_set:47,
                 from /home/intrainos/ZncTwitchTMI/twitchtmi.h:6,
                 from /home/intrainos/ZncTwitchTMI/twitchtmi.cpp:12:
/usr/include/c++/4.8/bits/hashtable_policy.h:1070:12: error: invalid use of incomplete type ‘struct std::hash<CString>’
     struct _Hash_code_base<_Key, _Value, _ExtractKey, _H1, _H2,
            ^
In file included from /usr/include/c++/4.8/bits/basic_string.h:3033:0,
                 from /usr/include/c++/4.8/string:52,
                 from /usr/include/c++/4.8/stdexcept:39,
                 from /usr/include/c++/4.8/array:38,
                 from /usr/include/c++/4.8/tuple:39,
                 from /usr/include/c++/4.8/bits/stl_map.h:63,
                 from /usr/include/c++/4.8/map:61,
                 from /usr/local/include/znc/ZNCString.h:21,
                 from /usr/local/include/znc/Utils.h:21,
                 from /usr/local/include/znc/User.h:21,
                 from /home/intrainos/ZncTwitchTMI/twitchtmi.cpp:2:
/usr/include/c++/4.8/bits/functional_hash.h:58:12: error: declaration of ‘struct std::hash<CString>’
     struct hash;
            ^
In file included from /usr/include/c++/4.8/bits/hashtable.h:35:0,
                 from /usr/include/c++/4.8/unordered_set:47,
                 from /home/intrainos/ZncTwitchTMI/twitchtmi.h:6,
                 from /home/intrainos/ZncTwitchTMI/twitchtmi.cpp:12:
/usr/include/c++/4.8/bits/hashtable_policy.h:1082:53: error: invalid use of incomplete type ‘struct std::hash<CString>’
       using __ebo_h1 = _Hashtable_ebo_helper<1, _H1>;
                                                     ^
In file included from /usr/include/c++/4.8/bits/basic_string.h:3033:0,
                 from /usr/include/c++/4.8/string:52,
                 from /usr/include/c++/4.8/stdexcept:39,
                 from /usr/include/c++/4.8/array:38,
                 from /usr/include/c++/4.8/tuple:39,
                 from /usr/include/c++/4.8/bits/stl_map.h:63,
                 from /usr/include/c++/4.8/map:61,
                 from /usr/local/include/znc/ZNCString.h:21,
                 from /usr/local/include/znc/Utils.h:21,
                 from /usr/local/include/znc/User.h:21,
                 from /home/intrainos/ZncTwitchTMI/twitchtmi.cpp:2:
/usr/include/c++/4.8/bits/functional_hash.h:58:12: error: declaration of ‘struct std::hash<CString>’
     struct hash;
            ^
In file included from /usr/include/c++/4.8/bits/hashtable.h:35:0,
                 from /usr/include/c++/4.8/unordered_set:47,
                 from /home/intrainos/ZncTwitchTMI/twitchtmi.h:6,
                 from /home/intrainos/ZncTwitchTMI/twitchtmi.cpp:12:
/usr/include/c++/4.8/bits/hashtable_policy.h:1082:53: error: invalid use of incomplete type ‘struct std::hash<CString>’
       using __ebo_h1 = _Hashtable_ebo_helper<1, _H1>;
                                                     ^
In file included from /usr/include/c++/4.8/bits/basic_string.h:3033:0,
                 from /usr/include/c++/4.8/string:52,
                 from /usr/include/c++/4.8/stdexcept:39,
                 from /usr/include/c++/4.8/array:38,
                 from /usr/include/c++/4.8/tuple:39,
                 from /usr/include/c++/4.8/bits/stl_map.h:63,
                 from /usr/include/c++/4.8/map:61,
                 from /usr/local/include/znc/ZNCString.h:21,
                 from /usr/local/include/znc/Utils.h:21,
                 from /usr/local/include/znc/User.h:21,
                 from /home/intrainos/ZncTwitchTMI/twitchtmi.cpp:2:
/usr/include/c++/4.8/bits/functional_hash.h:58:12: error: declaration of ‘struct std::hash<CString>’
     struct hash;
            ^
In file included from /usr/local/include/znc/znc.h:22:0,
                 from /usr/local/include/znc/IRCNetwork.h:24,
                 from /home/intrainos/ZncTwitchTMI/twitchtmi.cpp:3:
/home/intrainos/ZncTwitchTMI/twitchtmi.h: In constructor ‘std::unordered_set<_Value, _Hash, _Pred, _Alloc>::unordered_set(std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Value = CString; _Hash = std::hash<CString>; _Pred = std::equal_to<CString>; _Alloc = std::allocator<CString>; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::hasher = std::hash<CString>; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<CString>; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<CString>]’:
/home/intrainos/ZncTwitchTMI/twitchtmi.h:18:2: error: invalid use of incomplete type ‘std::unordered_set<CString>::hasher {aka struct std::hash<CString>}’
  MODCONSTRUCTOR(TwitchTMI) { lastFrankerZ = 0; }
  ^
In file included from /usr/include/c++/4.8/bits/basic_string.h:3033:0,
                 from /usr/include/c++/4.8/string:52,
                 from /usr/include/c++/4.8/stdexcept:39,
                 from /usr/include/c++/4.8/array:38,
                 from /usr/include/c++/4.8/tuple:39,
                 from /usr/include/c++/4.8/bits/stl_map.h:63,
                 from /usr/include/c++/4.8/map:61,
                 from /usr/local/include/znc/ZNCString.h:21,
                 from /usr/local/include/znc/Utils.h:21,
                 from /usr/local/include/znc/User.h:21,
                 from /home/intrainos/ZncTwitchTMI/twitchtmi.cpp:2:
/usr/include/c++/4.8/bits/functional_hash.h:58:12: error: declaration of ‘std::unordered_set<CString>::hasher {aka struct std::hash<CString>}’
     struct hash;
            ^
In file included from /usr/local/include/znc/znc.h:22:0,
                 from /usr/local/include/znc/IRCNetwork.h:24,
                 from /home/intrainos/ZncTwitchTMI/twitchtmi.cpp:3:
/home/intrainos/ZncTwitchTMI/twitchtmi.h:18:2: note:   when instantiating default argument for call to std::unordered_set<_Value, _Hash, _Pred, _Alloc>::unordered_set(std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Value = CString; _Hash = std::hash<CString>; _Pred = std::equal_to<CString>; _Alloc = std::allocator<CString>; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::hasher = std::hash<CString>; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<CString>; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<CString>]
  MODCONSTRUCTOR(TwitchTMI) { lastFrankerZ = 0; }
  ^
In file included from /usr/include/c++/4.8/bits/hashtable.h:35:0,
                 from /usr/include/c++/4.8/unordered_set:47,
                 from /home/intrainos/ZncTwitchTMI/twitchtmi.h:6,
                 from /home/intrainos/ZncTwitchTMI/twitchtmi.cpp:12:
/usr/include/c++/4.8/bits/hashtable_policy.h: In instantiation of ‘std::__detail::_Hash_code_base<_Key, _Value, _ExtractKey, _H1, _H2, std::__detail::_Default_ranged_hash, true>::__hash_code std::__detail::_Hash_code_base<_Key, _Value, _ExtractKey, _H1, _H2, std::__detail::_Default_ranged_hash, true>::_M_hash_code(const _Key&) const [with _Key = CString; _Value = CString; _ExtractKey = std::__detail::_Identity; _H1 = std::hash<CString>; _H2 = std::__detail::_Mod_range_hashing; std::__detail::_Hash_code_base<_Key, _Value, _ExtractKey, _H1, _H2, std::__detail::_Default_ranged_hash, true>::__hash_code = long unsigned int]’:
/usr/include/c++/4.8/bits/hashtable.h:1023:50:   required from ‘std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::iterator std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::find(const key_type&) [with _Key = CString; _Value = CString; _Alloc = std::allocator<CString>; _ExtractKey = std::__detail::_Identity; _Equal = std::equal_to<CString>; _H1 = std::hash<CString>; _H2 = std::__detail::_Mod_range_hashing; _Hash = std::__detail::_Default_ranged_hash; _RehashPolicy = std::__detail::_Prime_rehash_policy; _Traits = std::__detail::_Hashtable_traits<true, true, true>; std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::iterator = std::__detail::_Node_iterator<CString, true, true>; std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::key_type = CString]’
/usr/include/c++/4.8/bits/unordered_set.h:517:29:   required from ‘std::unordered_set<_Value, _Hash, _Pred, _Alloc>::iterator std::unordered_set<_Value, _Hash, _Pred, _Alloc>::find(const key_type&) [with _Value = CString; _Hash = std::hash<CString>; _Pred = std::equal_to<CString>; _Alloc = std::allocator<CString>; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::iterator = std::__detail::_Node_iterator<CString, true, true>; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::key_type = CString]’
/home/intrainos/ZncTwitchTMI/twitchtmi.cpp:283:42:   required from here
/usr/include/c++/4.8/bits/hashtable_policy.h:1103:22: error: no match for call to ‘(const std::hash<CString>) (const CString&)’
       { return _M_h1()(__k); }
                      ^
/usr/include/c++/4.8/bits/hashtable_policy.h: In instantiation of ‘std::__detail::_Hash_code_base<_Key, _Value, _ExtractKey, _H1, _H2, std::__detail::_Default_ranged_hash, true>::_Hash_code_base(const _ExtractKey&, const _H1&, const _H2&, const std::__detail::_Default_ranged_hash&) [with _Key = CString; _Value = CString; _ExtractKey = std::__detail::_Identity; _H1 = std::hash<CString>; _H2 = std::__detail::_Mod_range_hashing]’:
/usr/include/c++/4.8/bits/hashtable_policy.h:1463:65:   required from ‘std::__detail::_Hashtable_base<_Key, _Value, _ExtractKey, _Equal, _H1, _H2, _Hash, _Traits>::_Hashtable_base(const _ExtractKey&, const _H1&, const _H2&, const _Hash&, const _Equal&) [with _Key = CString; _Value = CString; _ExtractKey = std::__detail::_Identity; _Equal = std::equal_to<CString>; _H1 = std::hash<CString>; _H2 = std::__detail::_Mod_range_hashing; _Hash = std::__detail::_Default_ranged_hash; _Traits = std::__detail::_Hashtable_traits<true, true, true>]’
/usr/include/c++/4.8/bits/hashtable.h:828:24:   required from ‘std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::_Hashtable(std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::size_type, const _H1&, const _H2&, const _Hash&, const _Equal&, const _ExtractKey&, const allocator_type&) [with _Key = CString; _Value = CString; _Alloc = std::allocator<CString>; _ExtractKey = std::__detail::_Identity; _Equal = std::equal_to<CString>; _H1 = std::hash<CString>; _H2 = std::__detail::_Mod_range_hashing; _Hash = std::__detail::_Default_ranged_hash; _RehashPolicy = std::__detail::_Prime_rehash_policy; _Traits = std::__detail::_Hashtable_traits<true, true, true>; std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::size_type = long unsigned int; std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::allocator_type = std::allocator<CString>]’
/usr/include/c++/4.8/bits/hashtable.h:397:26:   required from ‘std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::_Hashtable(std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::size_type, const _H1&, const key_equal&, const allocator_type&) [with _Key = CString; _Value = CString; _Alloc = std::allocator<CString>; _ExtractKey = std::__detail::_Identity; _Equal = std::equal_to<CString>; _H1 = std::hash<CString>; _H2 = std::__detail::_Mod_range_hashing; _Hash = std::__detail::_Default_ranged_hash; _RehashPolicy = std::__detail::_Prime_rehash_policy; _Traits = std::__detail::_Hashtable_traits<true, true, true>; std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::size_type = long unsigned int; std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::key_equal = std::equal_to<CString>; std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::allocator_type = std::allocator<CString>]’
/usr/include/c++/4.8/bits/unordered_set.h:136:35:   required from ‘std::unordered_set<_Value, _Hash, _Pred, _Alloc>::unordered_set(std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Value = CString; _Hash = std::hash<CString>; _Pred = std::equal_to<CString>; _Alloc = std::allocator<CString>; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::hasher = std::hash<CString>; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<CString>; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<CString>]’
/home/intrainos/ZncTwitchTMI/twitchtmi.h:18:2:   required from here
/usr/include/c++/4.8/bits/hashtable_policy.h:1099:63: error: invalid use of incomplete type ‘struct std::hash<CString>’
       : __ebo_extract_key(__ex), __ebo_h1(__h1), __ebo_h2(__h2) { }
                                                               ^
In file included from /usr/include/c++/4.8/bits/basic_string.h:3033:0,
                 from /usr/include/c++/4.8/string:52,
                 from /usr/include/c++/4.8/stdexcept:39,
                 from /usr/include/c++/4.8/array:38,
                 from /usr/include/c++/4.8/tuple:39,
                 from /usr/include/c++/4.8/bits/stl_map.h:63,
                 from /usr/include/c++/4.8/map:61,
                 from /usr/local/include/znc/ZNCString.h:21,
                 from /usr/local/include/znc/Utils.h:21,
                 from /usr/local/include/znc/User.h:21,
                 from /home/intrainos/ZncTwitchTMI/twitchtmi.cpp:2:
/usr/include/c++/4.8/bits/functional_hash.h:58:12: error: declaration of ‘struct std::hash<CString>’
     struct hash;
            ^
In file included from /usr/include/c++/4.8/bits/hashtable.h:35:0,
                 from /usr/include/c++/4.8/unordered_set:47,
                 from /home/intrainos/ZncTwitchTMI/twitchtmi.h:6,
                 from /home/intrainos/ZncTwitchTMI/twitchtmi.cpp:12:
/usr/include/c++/4.8/bits/hashtable_policy.h:1099:63: error: invalid use of incomplete type ‘struct std::hash<CString>’
       : __ebo_extract_key(__ex), __ebo_h1(__h1), __ebo_h2(__h2) { }
                                                               ^
In file included from /usr/include/c++/4.8/bits/basic_string.h:3033:0,
                 from /usr/include/c++/4.8/string:52,
                 from /usr/include/c++/4.8/stdexcept:39,
                 from /usr/include/c++/4.8/array:38,
                 from /usr/include/c++/4.8/tuple:39,
                 from /usr/include/c++/4.8/bits/stl_map.h:63,
                 from /usr/include/c++/4.8/map:61,
                 from /usr/local/include/znc/ZNCString.h:21,
                 from /usr/local/include/znc/Utils.h:21,
                 from /usr/local/include/znc/User.h:21,
                 from /home/intrainos/ZncTwitchTMI/twitchtmi.cpp:2:
/usr/include/c++/4.8/bits/functional_hash.h:58:12: error: declaration of ‘struct std::hash<CString>’
     struct hash;
            ^
make[2]: **\* [CMakeFiles/twitch.dir/twitchtmi.cpp.o] Error 1
make[1]: **\* [CMakeFiles/twitch.dir/all] Error 2
make: **\* [all] Error 2

**Comment by TimoRoth** [comment]
Those errors are in your stdlib, I only ever tested this with gcc 4.9, so 4.8 is probably just too old.
