### ISSUE TITLE
how to install? 

### ISSUE THREAD

**Issue by ghost** [BtbN/ZncTwitchTMI#4]
hi!
after compiling with "znc-buildmod twitchtmi.cpp", i put the resulting .so file into ~/.znc/modules, but i don't see any way to activate it within ZNC web portal. what am i doing wrong? 

Version: ZNC 1.7.x-nightly-20170324-aefc97d0
http://wiki.znc.in/Compiling_modules

**Comment by BtbN** [comment]
You need to build with the provided cmake build system, otherwise you get an incomplete module.
